# Auto Date Table
Using Power Query, this code allows for dynamic generation of date columns, especially for inserting in a dedicated table apart from the facts or diemnsion tables in the final model.

This code was made following [Fernan's Power Query tutorial](https://www.youtube.com/watch?v=lTH2C--5xgo&t=1s) and adding some more columns.
```
let
    StartDate = Date.AddYears(Date.From(DateTime.LocalNow()), -1),
    EndDate = Date.AddYears(Date.From(DateTime.LocalNow()), 1),
    NumberOfDays = Duration.Days(EndDate - StartDate),
    Dates = List.Dates(StartDate, NumberOfDays + 1, #duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type", {"Column1", "Full Date"}),
    #"Inserted Day" = Table.AddColumn(#"Renamed Columns", "Day", each Date.Day([Full Date]), Int64.Type),
    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Full Date]), type text),
    #"Inserted Month" = Table.AddColumn(#"Inserted Day Name", "Month", each Date.Month([Full Date]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Full Date]), type text),
    #"Inserted Year" = Table.AddColumn(#"Inserted Month Name", "Year", each Date.Year([Full Date]), Int64.Type),
    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year", "Quarter", each Date.QuarterOfYear([Full Date]), Int64.Type)
in
    #"Inserted Quarter"
```
- The ```StartDate``` and ```EndDate``` are dynamic as calculations are performed with ```DateTime.LocalNow()```, which is a **datetime** type (e.g. 2026-03-05 15:33:57), later converted into **date** (2026-03-05) by ```Date.From```, rendering it usable by ```Date.AddYears```. 
> **Note**
> Instead of writing or copy/pasting the query on every model, the best use would be publishing in 

